// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dao/i_jwt.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	system "accessToken/model/system"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenDao is a mock of TokenDao interface.
type MockTokenDao struct {
	ctrl     *gomock.Controller
	recorder *MockTokenDaoMockRecorder
}

// MockTokenDaoMockRecorder is the mock recorder for MockTokenDao.
type MockTokenDaoMockRecorder struct {
	mock *MockTokenDao
}

// NewMockTokenDao creates a new mock instance.
func NewMockTokenDao(ctrl *gomock.Controller) *MockTokenDao {
	mock := &MockTokenDao{ctrl: ctrl}
	mock.recorder = &MockTokenDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenDao) EXPECT() *MockTokenDaoMockRecorder {
	return m.recorder
}

// CreateTokenRecord mocks base method.
func (m *MockTokenDao) CreateTokenRecord(ctx *gin.Context, token string, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTokenRecord", ctx, token, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTokenRecord indicates an expected call of CreateTokenRecord.
func (mr *MockTokenDaoMockRecorder) CreateTokenRecord(ctx, token, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTokenRecord", reflect.TypeOf((*MockTokenDao)(nil).CreateTokenRecord), ctx, token, userId)
}

// GetRecordById mocks base method.
func (m *MockTokenDao) GetRecordById(ctx *gin.Context, userId int) (*system.TokenDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordById", ctx, userId)
	ret0, _ := ret[0].(*system.TokenDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordById indicates an expected call of GetRecordById.
func (mr *MockTokenDaoMockRecorder) GetRecordById(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordById", reflect.TypeOf((*MockTokenDao)(nil).GetRecordById), ctx, userId)
}
