// Code generated by goctl. DO NOT EDIT.
// Source: access.proto

package server

import (
	"context"

	"accessToken_grpc/internal/logic"
	"accessToken_grpc/internal/svc"
	"accessToken_grpc/pb/token"
)

type AccessServer struct {
	svcCtx *svc.ServiceContext
	token.UnimplementedAccessServer
}

func NewAccessServer(svcCtx *svc.ServiceContext) *AccessServer {
	return &AccessServer{
		svcCtx: svcCtx,
	}
}

func (s *AccessServer) GenToken(ctx context.Context, in *token.GenReq) (*token.TokenResp, error) {
	l := logic.NewGenTokenLogic(ctx, s.svcCtx)
	return l.GenToken(in)
}

func (s *AccessServer) FreezeToken(ctx context.Context, in *token.TokenReq) (*token.TokenResp, error) {
	l := logic.NewFreezeTokenLogic(ctx, s.svcCtx)
	return l.FreezeToken(in)
}

func (s *AccessServer) ResetToken(ctx context.Context, in *token.TokenReq) (*token.TokenResp, error) {
	l := logic.NewResetTokenLogic(ctx, s.svcCtx)
	return l.ResetToken(in)
}

func (s *AccessServer) VerifyToken(ctx context.Context, in *token.TokenReq) (*token.TokenResp, error) {
	l := logic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}
