// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	token "accessToken_go_zero/internal/handler/token"
	"accessToken_go_zero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/freezeTokenHandler",
				Handler: token.FreezeTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/genToken",
				Handler: token.GenTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resetToken",
				Handler: token.ResetTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verifyTokenHandler",
				Handler: token.VerifyTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/token"),
	)
}
